// Official program pages checked on 2026-10-04. Editorial summaries are not approvals.
const HRS = 'https://www.homerenovationsavings.ca/without-assessment/heat-pumps';
const TERMS = 'https://www.homerenovationsavings.ca/terms-and-conditions';
const EAP = 'https://saveonenergy.ca/en/For-Your-Home/Energy-Affordability-Program';
const OHPA = 'https://natural-resources.canada.ca/energy-efficiency/home-energy-efficiency/canada-greener-homes-initiative/applicants-participating-provinces-territories';
const LOAN = 'https://natural-resources.canada.ca/energy-efficiency/home-energy-efficiency/canada-greener-homes-initiative/grant-process-works';
const link = (url,label) => `<a href="${url}" rel="noopener">${label}</a>`;
const list = items => `<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const section = (heading,body) => `<h2>${heading}</h2>${body}`;
const para = text => `<p>${text}</p>`;
const wrap = (h1,html) => `<section class="hpro-section"><div class="hpro-wrap hpro-prose" style="max-width:900px"><h1>${h1}</h1>${html}</div></section>`;
const calc = '<p>If the home already uses a heat pump for space heating, HRS will not fund its replacement. Check this before deducting any heat pump cap from the quote.</p><div class="hpro-calc-mount" data-hpro-calc></div>';
const checked = '<p class="hpro-verified">Program sources checked October 4, 2026. The program administrator decides eligibility; confirm current terms before ordering equipment.</p>';
export function buildContent({ brand, contactForm }) {
 const pages=[];
 const add=(url,title,desc,html,extra={})=>pages.push({url,title:`${title} | ${brand}`,desc,body:wrap(title,html),...extra});
 const noFurnace=para(`The current HRS heat pump stream does not rebate a standalone gas furnace or a cooling-only air conditioner. A compatible furnace can form part of a heat pump system, but backup heating is not itself an eligible rebate measure. ${link(TERMS,'Check the official program requirements')} before a rebate is deducted from a furnace quote.`);
 add('/','Ontario furnace replacement: check the rebate claim first','Learn why a standalone gas furnace is not an HRS heat pump rebate and compare repair, replacement and hybrid options.',
  para('If your furnace needs replacing, start by separating the equipment you need from the incentive a salesperson mentions. A new gas furnace, a heat pump added to an existing furnace, and a full electric heating conversion are different projects with different budgets. This guide helps you compare them.')+
  section('Does a new gas furnace qualify?',noFurnace)+
  section('Compare three decisions',list(['Repair the current furnace when the fault and remaining condition justify it.','Replace the furnace on its own, budgeting the full price without an assumed HRS furnace rebate.','Consider a qualifying heat pump project, with an appropriate backup and control plan, before committing to either equipment purchase.']))+
  section('Read the estimate line by line',para('Ask the contractor to separate furnace equipment, heat pump equipment, installation, electrical or duct changes, taxes and anticipated funding. Keep the gross price visible. A rebate listed as a discount still needs a named program, approved equipment and the required application process.'))+
  section('Explore heat pump funding separately',para('The checker is for heat pump program caps. It cannot quote a rebate for a furnace-only replacement.')+calc)+checked);
 add('/how-it-works/','How to compare a furnace quote with a hybrid option','A decision process for furnace repair, replacement or heat pump conversion before accepting a quote.',
  section('Establish what has failed',para('Ask for the diagnosed fault, the proposed repair and an explanation of the condition of the rest of the furnace. Replacing an inexpensive failed component and replacing a deteriorated system are different recommendations. Have the provider explain the evidence supporting either choice.'))+
  section('Compare the full alternatives',para('Request a standalone furnace price and, where suitable, a separate heat pump or hybrid design. Check the proposed capacity, indoor equipment, controls and work needed at the panel or ducts. Compare gross installed costs before any rebate or finance payment is shown.'))+
  section('Verify funding before installation',para('When a qualifying heat pump is included, a participating HRS contractor submits a pre-installation application. Approval must arrive before installation. A furnace-only job cannot be made eligible merely by calling its price an HVAC upgrade.'))+
  section('Document the final choice',list(['Record what is kept and what is replaced.','List model numbers and exclusions.','Identify who submits each application.','Keep approvals and the paid invoice.']))+para(link(HRS,'Current heat pump application steps'))+checked);
 add('/who-qualifies/','Which furnace-related projects may use heat pump rebates?','Separate furnace-only work, compatible backup heating and eligible HRS heat pump projects.',
  section('Furnace-only replacement',para('Do not claim the HRS heat pump rebate against a new gas furnace on its own. A furnace repair, blower replacement or thermostat adjustment also does not become a heat pump installation because it improves comfort.'))+
  section('A furnace paired with a qualifying heat pump',para('The heat pump project needs a qualified equipment combination and a participating contractor. The program permits compatible backup heating under its requirements, but does not rebate the backup furnace as an eligible measure. Ask for the rebate calculation to identify the heat pump rather than the furnace price.'))+
  section('Check whether a heat pump is already installed',para('If the home already uses a heat pump for space heating, HRS will not fund its replacement. Check this before deducting any heat pump cap from the quote.'))+
  section('The home still has to qualify',para('For natural-gas heating, HRS requires an active Enbridge residential account. Other primary fuels use the Ontario-grid requirement. Homeownership, the eligible home types, the exclusion for very new homes and pre-approval also apply. Eligibility is not established by the presence of any gas appliance.'))+para(`${link(HRS,'Review the home and fuel requirements')} and ${link(TERMS,'the detailed terms')}.`)+checked);
 add('/rebate-calculator/','Check heat pump caps, then compare the furnace budget','This checker covers heat pump caps and does not assign a rebate to a standalone furnace.',
  para('Choose your existing primary heating source to view the published heat pump caps. If your plan is to replace only the gas furnace or a cooling-only AC, no HRS heat pump rebate should be inserted into that quote.')+calc+
  section('A cap is not a net installed price',para('The final system, rated capacity and program approval control the amount. Obtain the gross quote first, then put any verified heat pump incentive on a separate line. For a rental arrangement, ask for the rental rates and total contract cost rather than applying the purchased-system maximum.'))+checked);
 add('/contact/','Send a furnace or hybrid quote question','Ask about a furnace quote, existing equipment and any heat pump rebate line.',
  para('Include whether you need a furnace repair, a furnace-only replacement, or a heat pump paired with a furnace. If a quote deducts a rebate, tell us the program name and which equipment appears on that line. Remove account numbers and personal documents before sharing details.')+contactForm+
  section('An inquiry is not an application',para('A response can help you organize questions for a provider. Program administrators approve funding, while you agree on equipment, scope and price with the contractor.')),{scripts:['/assets/js/contact-form.js']});
 add('/thank-you/','Your heating quote question was received','Your furnace or hybrid project inquiry has been received.',
  para('Save the itemized quote and the diagnostic findings while your inquiry is reviewed. Check whether any incentive is attributed to a heat pump or incorrectly to a furnace-only replacement. If a qualifying heat pump is planned, confirm pre-approval before the installation date.')+para('<a href="/how-it-works/">Compare the project choices</a>.'),{noindex:true});
 add('/rebates-explained/','Furnace quotes and Ontario incentive programs','Which incentive claims belong in a furnace quote, what needs a heat pump and what is closed.',
  noFurnace+
  section('Program names do not replace scope',para('An HRS heat pump claim needs qualifying heat pump equipment. Ontario oil-heating affordability support is a separate direct-install pathway. The older Enbridge program names found in search results may describe past offers. New Canada Greener Homes Loan applications are closed.'))+
  section('Use the relevant explanation',list(['<a href="/rebates/home-renovation-savings-program/">HRS and a furnace used as backup</a>.','<a href="/rebates/oil-to-heat-pump-affordability/">Oil furnace households: investigate the official direct-install route</a>.','<a href="/rebates/enbridge-home-efficiency-rebate/">Legacy Enbridge offers in current sales material</a>.','<a href="/rebates/canada-greener-homes-loan/">Why new federal loan funding cannot be assumed</a>.','<a href="/rebates/municipal-utility-programs/">Confirm finance terms at your own municipality</a>.']))+
  section('Avoid counting money twice',para('A quoted equipment discount, a loan and a program rebate may all appear in a financing discussion. They are different amounts. Ask which is a price reduction, which is repayable and which still requires approval.'))+checked);
 add('/faq/','Furnace and hybrid quote questions','Answers about furnace-only rebates, existing furnaces, emergency replacement and quote comparisons.',
  section('Is a more efficient gas furnace an HRS heat pump?',para('No. HRS heat pump funding requires a qualifying heat pump installation. Improving a gas furnace\'s efficiency does not change its equipment category.'))+
  section('Must I replace the furnace to add a heat pump?',para('The current requirements allow either an existing or new compatible furnace for specified hybrid arrangements. The contractor must check the equipment match and controls. Keeping an unsuitable component is not a useful saving.'))+
  section('Can I buy the furnace now and sort out a heat pump rebate later?',para('Treat later work as a new design and funding decision. HRS installations need pre-approval, and equipment purchased without considering a future heat pump may limit compatible choices. Ask about the complete plan before placing orders.'))+
  section('What if I need heat restored urgently?',para('Discuss the immediate repair and any replacement options with the responding provider. Do not let a promised rebate delay a necessary safety decision; do not assume an emergency waives program pre-approval.'))+
  section('How should a rebate appear on the estimate?',para('Keep the gross installed price and a separate anticipated incentive. The quote should name the program and identify the equipment and approvals on which the incentive depends.'))+checked);
 add('/about/','Why this guide starts with the furnace quote','An independent guide for Ontario homeowners comparing furnace replacement and heat pump options.',
  para('Ontario Furnace Rebates addresses a common confusion in heating sales: a rebate available for a heat pump is sometimes described as though it paid for any furnace upgrade. We organize the decision around the existing heater, the proposed replacement and the exact scope behind a funding claim.')+
  section('The questions this site covers',para('A homeowner should be able to understand the reason for replacement, compare a repair with new equipment, separate furnace and heat pump costs, and identify any application that must be approved before work. These are the questions our guides emphasize.'))+
  section('Our role in a project',para('This is an independent information and inquiry site. It is not a government office, a funding administrator or proof of a contractor\'s registration. Use official directories and the provider\'s documents to verify qualifications, insurance, scope and participation.'))+
  section('Keep control of the purchase',para('A form request does not commit you to equipment, finance or installation. Ask for an itemized written estimate and read the full contract. Neither a monthly payment nor a maximum program amount tells you the total price of the work.')));
 add('/rebates/home-renovation-savings-program/','HRS: the heat pump can qualify, the backup furnace does not','How HRS handles a furnace paired with a qualifying heat pump.',noFurnace+
  section('Separate the two equipment roles',para('A hybrid proposal has a heat pump to provide heating and cooling and a furnace that supplies backup heat when required. Both must work together safely and as intended. Program requirements permit new or existing backup equipment in specified arrangements, while excluding backup heating from the eligible rebate measure.'))+
  section('Read the rebate calculation',para('For an Enbridge natural-gas home purchasing a qualifying cold climate air source heat pump, the published rate is $500 per ton up to $2,000. The ground-source rate is $3,000. These figures describe heat pump funding, not a gas furnace rebate.'))+
  section('Before approving the quote',list(['Name the complete heat pump equipment combination.','Identify the furnace that remains or is replaced.','Show the heat pump incentive separately.','Wait for HRS pre-approval before installation.']))+para(link(HRS,'Official rates and application process'))+checked);
 add('/rebates/oil-to-heat-pump-affordability/','Before replacing an oil furnace, check Ontario support','Ontario oil-heated households may have an official no-cost heat pump installation route.',
  para('A failing oil furnace creates an immediate equipment decision. Before committing to another oil system or an independently purchased heat pump, an income-qualified household should check the official Ontario affordability route and discuss the urgency with its delivery agent.')+
  section('A managed installation, not a furnace rebate',para(`${link(OHPA,'NRCan describes Ontario\'s co-delivery arrangement')} through IESO. Eligible households can receive a directly installed heat pump system with a published project value up to $25,000. Applicants do not receive that value as cash. This should not be advertised as a $25,000 discount on an oil furnace.`))+
  section('Ask the official delivery program',para(`${link(EAP,'Save on Energy Energy Affordability')} checks the household and property and uses its own assessment and installation process. The federal portal deadline is not the correct application route for a new Ontario co-delivery applicant; confirm provincial intake directly.`))+
  section('If a purchase has already been agreed',para('Tell the delivery agent about the signed contract and any equipment order. Do not assume a direct-install program will reimburse a private purchase after the event.'))+checked);
 add('/rebates/enbridge-home-efficiency-rebate/','Check old Enbridge rebate claims on a new furnace quote','Identify outdated rebate references and ask for the current terms supporting a furnace sales offer.',
  para('A brochure or estimate may use Home Efficiency Rebate, HER+ or another legacy name. Treat the date and current program conditions as part of the sales claim. The fact that Enbridge administered a previous offer does not establish funding for a furnace being installed now.')+
  section('Questions for the salesperson',list(['Where are the current published terms?','Which measure in this quote is eligible?','Is the incentive for a heat pump rather than the furnace?','Who applies and what approval is needed before work?','Does the quoted price depend on your receiving a rebate?']))+
  section('Put the answer in writing',para('If the provider cannot identify a current eligible measure, compare the purchase at its full gross price. Do not accept an oral promise that a program will reimburse an unspecified HVAC upgrade.'))+para(`For new heat pump work, use ${link(HRS,'the current HRS heat pump page')}.`)+checked);
 add('/rebates/canada-greener-homes-loan/','Do not budget a new furnace project around the closed federal loan','New Canada Greener Homes Loan applications closed October 1, 2025.',
  para(`The ${link(LOAN,'official federal process')} records the last date for a new Canada Greener Homes Loan application as October 1, 2025. A new 2026 quote should not promise access to a newly approved interest-free federal loan.`)+
  section('Read the finance offer actually being sold',para('A contractor payment plan may instead be a private credit or rental agreement. Ask for the lender or lessor, total obligation, interest, fees, equipment ownership and early-exit conditions. A familiar federal program name must not substitute for those documents.'))+
  section('Compare purchase and rental on the same basis',para('Write down the gross purchase cost and the total required payments under any agreement. If a heat pump rebate is also shown, check the rental-specific program rates. A purchased-system incentive does not establish what a rental customer receives.'))+
  section('Existing federal borrowers',para('If you already had an approved federal loan, follow its agreement and account instructions. That existing file is separate from the sales offer for a new customer.'))+checked);
 add('/rebates/municipal-utility-programs/','Local finance questions for a heating replacement','Verify whether municipal support covers your heating project and how any loan is repaid.',
  para('Municipal financing should be checked against the actual equipment and property. An eligible energy retrofit loan is not automatically a cash rebate for a gas furnace, and availability may depend on the address, owner and current funding intake.')+
  section('Before signing a heating contract',list(['Ask whether the proposed furnace-only, hybrid or electric project is eligible.','Confirm whether an assessment or prior approval is required.','Check interest, repayment collection and any property lien.','Ask what happens to the obligation when the property is sold.','Obtain the rules about combining local funding with an equipment rebate.']))+
  section('Who can confirm it?',para('Use your own municipality\'s official program page or staff contact. A provider working in several cities may mention a financing scheme that does not cover your address. Budget at the full price until that detail is confirmed.'))+checked);
 const cities=[
 ['toronto','Toronto','Access and removal in a constrained property','When a heating replacement involves a narrow stair, shared entrance or limited mechanical room, ask how the old equipment will leave and the new equipment will enter. Access labour and property protection should appear in the scope rather than emerge as a surprise on installation day.','For a hybrid option, also identify outdoor-unit placement and the route for refrigerant lines. The furnace replacement and heat pump work have different physical requirements, so compare complete scopes.',['Measure doors and stairs.','Identify items that must move before the visit.','List protection and disposal in the quote.']],
 ['ottawa','Ottawa','Backup heating controls in a hybrid quote','A proposal that keeps a gas furnace and adds a heat pump needs a clear control sequence. Ask when the system changes from heat pump operation to backup heat and how the thermostat makes that decision.','Have the contractor explain the relationship between the building load, low-temperature output and backup operation. A rebate is a funding calculation; it does not decide the comfort settings for your home.',['Record the thermostat and controls.','Ask about the chosen transition settings.','Keep commissioning instructions with the invoice.']],
 ['mississauga','Mississauga','Retaining a working furnace while replacing cooling','If the furnace is serviceable but the cooling equipment has failed, ask whether a compatible heat pump option can be designed around the existing indoor system. Compare that with a cooling-only replacement and a complete furnace replacement.','The correct equipment match needs checking before quoting an incentive. Keeping a furnace simply because its cabinet fits does not establish heat pump compatibility or rebate eligibility.',['Get the furnace model and condition findings.','Ask for the full coil and outdoor-unit match.','Price each alternative before funding.']],
 ['hamilton','Hamilton','Duct repairs versus a larger furnace','Weak heat in one room does not by itself show that the furnace is too small. Distribution issues can remain after new equipment is installed. Ask how the provider distinguished a capacity problem from restricted airflow or a control issue.','If duct changes are required, identify them as part of the scope and cost. A hybrid heat pump design may have different airflow needs from the existing furnace arrangement.',['List the rooms with symptoms.','Ask what airflow checks were performed.','Separate distribution repairs from equipment.']],
 ['london','London','A diagnostic repair price alongside replacement','Before accepting a replacement recommendation, request the fault and repair price in writing. The condition of the heat exchanger, combustion components and other equipment should be assessed by the qualified responding provider.','Compare the repair with a gross furnace replacement price and, if appropriate, a designed heat pump option. A funding maximum should not make a more expensive project look unavoidable when the actual alternatives have not been explained.',['Keep the diagnostic findings.','Compare warranties and exclusions.','Show anticipated rebates on separate lines.']],
 ['brampton','Brampton','Heating work while occupants remain in the home','For an occupied rental property, the owner and occupants need a plan for access, heating interruption and restoration. Establish which spaces share the furnace and whether the work affects more than one dwelling area.','If a qualifying heat pump is proposed, the owner applies for HRS, and the property arrangement still needs eligibility review. Do not infer approval from the fact that a tenant pays a utility bill.',['Identify the owner responsible for the project.','Agree on access with occupants.','Describe any shared equipment or entrances.']],
 ['kitchener-waterloo','Kitchener-Waterloo','Comparing an electric furnace with a heat pump','An electric resistance furnace and an electric heat pump both use electricity but operate differently. When replacing an electric furnace, ask for a complete heat pump design and any backup requirements rather than treating the equipment names as interchangeable.','The current primary heating category matters for the HRS heat pump rate. The exact proposed system and pre-approval matter too; a new electric furnace alone is not a cold climate heat pump.',['Identify resistance heating in the current system.','Ask what backup remains.','Check the qualified model combination.']],
 ['windsor','Windsor','Coordinating heating and cooling replacement','If both the furnace and air conditioner are ageing, compare the two-replacement scope with a suitable heat pump system and its backup. Ask which indoor equipment, electrical work and control changes each alternative includes.','A cooling-only AC does not become eligible for HRS heat pump funding. Keep the funding line tied to the qualified heat pump, and compare gross costs before advertised monthly payments.',['Compare complete installed scopes.','Ask how humidity and cooling needs are addressed.','Check ownership and total finance cost.']],
 ['barrie','Barrie','Scheduling a heating replacement before a loss of heat','A planned replacement allows time for diagnosis, design and any heat pump pre-approval. An urgent failure compresses those decisions. Ask the responding provider what temporary repair or heating options are reasonable for the condition it finds.','Do not assume emergency circumstances waive HRS pre-approval. If a heat pump is part of the long-term plan, discuss the approval sequence alongside the immediate need for reliable heat.',['Record the immediate fault.','Ask about repair and replacement timing.','Confirm application approval before heat pump installation.']],
 ['kingston','Kingston','Checking whether the home uses a furnace or a boiler','A ducted furnace heats air; a boiler heats water for radiators or other hydronic distribution. A heating quote must match what the property actually has. An air source ducted proposal can require distribution changes in a home that uses radiators.','Identify the present system before comparing incentives and equipment prices. Ground source or other hydronic proposals need their own qualified equipment and installation review; a generic furnace package is not an interchangeable solution.',['Photograph equipment labels.','Describe radiators, ducts or baseboards.','Ask for all conversion work in the price.']]
 ];
 for(const [slug,city,topic,p1,p2,items] of cities) add(`/furnace-rebate-${slug}/`,`Furnace planning in ${city}: ${topic.toLowerCase()}`,`Compare a ${city} furnace project: ${topic.toLowerCase()}, scope and heat pump funding.`,para(p1)+section(topic,para(p2)+list(items))+section('Check the rebate line',para('A furnace-only replacement has no HRS heat pump rebate. If the proposal includes a qualifying heat pump, check its separate equipment, rate and mandatory pre-approval. The city does not create a special provincial furnace entitlement.'))+para('<a href="/rebates/home-renovation-savings-program/">How HRS treats a backup furnace</a> and <a href="/how-it-works/">how to compare the quotes</a>.')+checked);
 add('/hrs-2026-update/','October 2026: correct the incentive line on a furnace quote','Current furnace and heat pump incentive distinctions for Ontario replacement estimates.',
  section('Remove the furnace-only rebate assumption',para('The earlier site copy incorrectly described $1,000 to $2,000 as a high-efficiency gas furnace rebate. Current HRS heat pump rates apply to eligible heat pump equipment; backup furnaces are excluded as eligible measures. A new furnace budget should show the full price unless a separate current offer is documented.'))+
  section('Check the equipment and the agreement',para('A hybrid system may keep or replace the furnace, but it needs a suitable heat pump combination and controls. Rental equipment uses different heat pump caps from purchased equipment. Compare the scope and total agreement cost alongside the rebate.'))+
  section('Remove obsolete finance assumptions',para('Canada Greener Homes Loan intake closed October 1, 2025. Ontario oil-heating affordability support follows a managed direct-install path, not a promised $22,000 combined cash rebate. These changes belong in the written quote before a homeowner makes a decision.'))+para(`${link(TERMS,'HRS terms')} | ${link(OHPA,'Ontario affordability delivery')} | ${link(LOAN,'Federal loan status')}`)+checked);
 add('/blog/','Heating quote notes','Practical checks for furnace replacement and hybrid heating estimates.',para('<a href="/hrs-2026-update/">October 2026: correct the incentive line on a furnace quote</a>')+para('The guides on this site start with the diagnosed problem and the work proposed. Read them before comparing a full equipment price with an advertised rebate or a monthly finance payment.'));

 add('/privacy-policy/','Privacy and project inquiries','How information supplied to Ontario Furnace Rebates is used for project inquiries.',
  para('The optional calculator and contact form collect the details you enter, including name, email, phone, postal code, heating source and project description. A submission also includes its page URL and marketing-source parameters when present.')+
  section('Why the information is collected',para('Your details are used to review and follow up on a furnace and hybrid quote review inquiry. The site uses a Headbanger Marketing lead-processing workflow. A relevant service provider may receive the inquiry to respond to the work requested. A submission is not an official funding application.'))+
  section('Keep sensitive documents out of the form',para('Do not send identity numbers, income files, banking details, passwords or government-program account credentials here. If an official program needs evidence, submit it through that program\'s verified process.'))+
  section('Questions or changes',para('Use the contact form to ask about information you submitted or to request that follow-up stop. This notice describes the inquiry flow; a provider or official administrator may have a separate policy for its own services.')));
 add('/terms/','Terms for the furnace quote guide','Using furnace, hybrid heating and financing guidance before accepting an estimate.',
  section('Your estimate is a separate agreement',para('A guide on this website does not supply, install or warrant heating equipment. The written contract you make with a provider determines the work, price, schedule and warranty. Confirm the diagnosed fault and itemized alternatives directly with that provider. A form submission does not commit you to a purchase or authorize a visit.'))+
  section('Distinguish the incentive from the equipment price',para('The heat pump checker cannot assign an HRS rebate to a gas furnace, a furnace repair or a cooling-only air conditioner. A hybrid quote needs a qualified heat pump, compatible backup equipment and mandatory program approval. Keep the gross installed price visible even when an estimate lists anticipated funding.'))+
  section('Compare finance documents',para('A monthly payment does not establish total cost or equipment ownership. Read the actual lender or rental agreement, including fees, interest, repayment and early-exit terms. The closed Canada Greener Homes Loan should not be assumed available for a new application. Existing borrowers must follow their own approved file.'))+
  section('The limits of follow-up',para('Ontario Furnace Rebates is an independent information and inquiry site. Follow-up is not a funding decision. Current official program terms and the administrator determine eligibility; the responding provider must establish qualifications, insurance, program participation and the proposed scope with you.')));

 return pages;
}
